name: "Setup FerretDB Action"
description: "Handle / Start and stops FerretDB instance"

runs:
  using: "composite"
  steps:
    - name: Start ferretdb container
      run: docker run -d --rm --name ferretdb -p 27017:27017 --platform linux/amd64 ghcr.io/ferretdb/ferretdb-eval:2 
      shell: bash

    - name: Stop ferretdb container
      run: docker stop ferretdb
      shell: bash