name: "FerretDB instance management"
description: "Handle a FerretDB instance"

inputs:
  action:
    description: create or stop a FerretDB instance
    required: true
    default: "start"

runs:
  using: "composite"
  steps:
    - name: Start ferretdb container
      if: ${{ inputs.action == 'start' }}
      run: |
        docker run -d --rm --name ferretdb -p 27017:27017 --platform linux/amd64 ghcr.io/ferretdb/ferretdb-eval:2 
      shell: bash

    - name: Stop ferretdb container
      if: ${{ inputs.action == 'stop' }}
      run: |
        docker stop ferretdb
      shell: bash