name: Test FerretDB Instance management"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start FerretDB instance
        uses: ./

      - name: Stop FerretDB instance
        uses: ./
        with:
          action: "stop"